'use server';

/**
 * Finding mutations (task_plan.md Phase 5, D17/D23).
 *
 * Every write authenticates and authorizes server-side before touching the
 * database, runs inside a transaction, and appends an `activities` row with
 * the before/after diff (D13/D18). `activities` is append-only.
 *
 * Mutations created here are only those the UI actually uses — no placeholder
 * actions for future features.
 */

import { randomUUID } from 'node:crypto';
import { mkdir, unlink, writeFile } from 'node:fs/promises';

import { and, eq, isNull, isNotNull, sql } from 'drizzle-orm';

import { db } from '@/db/client';
import { activities, attachments, comments, findings } from '@/db/schema';
import { NotFoundError, ValidationError } from '@/lib/errors';
import { requireActorIdentity, requireRole } from '@/lib/rbac';
import { findingSchema, type FindingFormValues } from '../schemas/finding';
import type { ActivityAction, FindingStatus } from './types';
import { diffFields, hasChanges, type FieldDiff } from '../utils/diff';
import { resolveFile } from '../utils/file-type';
import { applyImport, type ImportSummary } from './import-core';

/** Attachment upload limit (task_plan.md §2/D25): 10 MB. */
const MAX_ATTACHMENT_BYTES = 10 * 1024 * 1024;

interface Actor {
  userId: string;
  email: string;
  name: string | null;
}

type Db = Parameters<Parameters<typeof db.transaction>[0]>[0];

/** Columns a manual edit may change; also the fields compared for the diff. */
const EDITABLE_FIELDS = [
  'noSatker',
  'tahun',
  'kodeTemuan',
  'kodeRekomendasi',
  'judulPemeriksaan',
  'uraianTemuan',
  'uraianRekomendasi',
  'nilaiTemuan',
  'status',
  'deskripsiTindakLanjut',
  'alasanDitolak',
  'tanggalTindakLanjut',
  'unitKerja'
] as const;

function parseInput(input: FindingFormValues) {
  const result = findingSchema.safeParse(input);
  if (!result.success) {
    throw new ValidationError(result.error.issues[0]?.message ?? 'Data temuan tidak valid.');
  }
  return result.data;
}

interface FindingRowInput {
  noSatker: string;
  tahun: number;
  kodeTemuan: string;
  kodeRekomendasi: string;
  judulPemeriksaan: string;
  uraianTemuan: string;
  uraianRekomendasi: string;
  nilaiTemuan: number;
  status: FindingStatus;
  deskripsiTindakLanjut: string;
  unitKerja: string;
  alasanDitolak?: string | null;
  tanggalTindakLanjut?: string | null;
}

function toRow(values: FindingRowInput) {
  return {
    noSatker: values.noSatker,
    tahun: values.tahun,
    kodeTemuan: values.kodeTemuan,
    kodeRekomendasi: values.kodeRekomendasi,
    judulPemeriksaan: values.judulPemeriksaan,
    uraianTemuan: values.uraianTemuan,
    uraianRekomendasi: values.uraianRekomendasi,
    // Exact numeric string — money never touches JS floating point (D8).
    nilaiTemuan: values.nilaiTemuan.toFixed(2),
    status: values.status,
    deskripsiTindakLanjut: values.deskripsiTindakLanjut,
    alasanDitolak: values.alasanDitolak ? values.alasanDitolak : null,
    tanggalTindakLanjut: values.tanggalTindakLanjut ? values.tanggalTindakLanjut : null,
    unitKerja: values.unitKerja
  };
}

async function logActivity(
  tx: Db,
  actor: Actor,
  entry: {
    entityId: string;
    entityType?: 'finding' | 'import_batch';
    action: ActivityAction;
    metadata: FieldDiff | Record<string, unknown>;
  }
) {
  await tx.insert(activities).values({
    entityType: entry.entityType ?? 'finding',
    entityId: entry.entityId,
    action: entry.action,
    metadata: entry.metadata,
    actorUserId: actor.userId,
    actorEmail: actor.email
  });
}

function isUniqueViolation(error: unknown): boolean {
  return (
    typeof error === 'object' && error !== null && (error as { code?: string }).code === '23505'
  );
}

export async function createFinding(input: FindingFormValues): Promise<{ kodeDisplay: string }> {
  await requireRole('editor');
  const values = parseInput(input);
  const actor = await requireActorIdentity();

  return db.transaction(async (tx) => {
    // `kode_display` is generated by the database trigger (D31).
    const [row] = await tx
      .insert(findings)
      // `kode_display` is filled by the BEFORE INSERT trigger (D31), so the
      // column is left to DEFAULT/NULL instead of being generated in the app.
      .values({ ...toRow(values), kodeDisplay: sql`default`, tanggalTerakhirUpdate: new Date() })
      .returning({ id: findings.id, kodeDisplay: findings.kodeDisplay });

    if (!row) {
      throw new ValidationError('Temuan gagal disimpan.');
    }

    await logActivity(tx, actor, {
      entityId: row.id,
      action: 'Tambah Temuan',
      metadata: { kodeDisplay: row.kodeDisplay }
    });

    return { kodeDisplay: row.kodeDisplay };
  });
}

export async function updateFinding(
  kodeDisplay: string,
  input: FindingFormValues
): Promise<{ changed: boolean; diff: FieldDiff }> {
  await requireRole('editor');
  const values = parseInput(input);
  const actor = await requireActorIdentity();

  return db.transaction(async (tx) => {
    const [current] = await tx
      .select()
      .from(findings)
      .where(and(eq(findings.kodeDisplay, kodeDisplay), isNull(findings.deletedAt)));

    if (!current) {
      throw new NotFoundError(`Temuan ${kodeDisplay} tidak ditemukan.`);
    }

    const row = toRow(values);
    const before = current as unknown as Record<string, unknown>;
    const after = { ...current, ...row } as unknown as Record<string, unknown>;
    const diff = diffFields(before, after, EDITABLE_FIELDS as unknown as string[]);

    if (!hasChanges(diff)) {
      return { changed: false, diff };
    }

    await tx.update(findings).set(row).where(eq(findings.id, current.id));
    await logActivity(tx, actor, {
      entityId: current.id,
      action: 'Perbarui Temuan',
      metadata: diff
    });

    return { changed: true, diff };
  });
}

export async function softDeleteFinding(kodeDisplay: string): Promise<{ deleted: boolean }> {
  await requireRole('editor');
  const actor = await requireActorIdentity();

  return db.transaction(async (tx) => {
    const [current] = await tx
      .select()
      .from(findings)
      .where(and(eq(findings.kodeDisplay, kodeDisplay), isNull(findings.deletedAt)));

    if (!current) {
      throw new NotFoundError(`Temuan ${kodeDisplay} tidak ditemukan.`);
    }

    await tx
      .update(findings)
      .set({ deletedAt: sql`now()` })
      .where(eq(findings.id, current.id));

    await logActivity(tx, actor, {
      entityId: current.id,
      action: 'Hapus Temuan',
      metadata: { kodeDisplay: current.kodeDisplay, softDelete: true }
    });

    return { deleted: true };
  });
}

/** Restore is admin-only (D12); never raw SQL by hand. */
export async function restoreFinding(kodeDisplay: string): Promise<{ restored: boolean }> {
  await requireRole('admin');
  const actor = await requireActorIdentity();

  return db.transaction(async (tx) => {
    const [current] = await tx
      .select()
      .from(findings)
      .where(and(eq(findings.kodeDisplay, kodeDisplay), isNotNull(findings.deletedAt)));

    if (!current) {
      throw new NotFoundError(`Temuan ${kodeDisplay} yang terhapus tidak ditemukan.`);
    }

    try {
      await tx.update(findings).set({ deletedAt: null }).where(eq(findings.id, current.id));
    } catch (error) {
      if (isUniqueViolation(error)) {
        throw new ValidationError(
          'Tidak bisa dipulihkan: sudah ada temuan aktif dengan identitas yang sama.'
        );
      }
      throw error;
    }

    await logActivity(tx, actor, {
      entityId: current.id,
      action: 'Pulihkan Temuan',
      metadata: { kodeDisplay: current.kodeDisplay }
    });

    return { restored: true };
  });
}

// ---------------------------------------------------------------------------
// XLSX import (D18/D19): auth + file validation here, the transactional core
// lives in `import-core.ts` so it can be integration tested without Clerk.
// ---------------------------------------------------------------------------

/** Imports are editor/admin only (D17). */
export async function importFindingsXlsx(formData: FormData): Promise<ImportSummary> {
  await requireRole('editor');
  const actor = await requireActorIdentity();

  const file = formData.get('file');
  if (!(file instanceof File)) {
    throw new ValidationError('Berkas XLSX wajib diunggah.');
  }
  if (!/\.(xlsx|xls)$/i.test(file.name)) {
    throw new ValidationError('Format berkas harus .xlsx atau .xls.');
  }

  const buffer = Buffer.from(await file.arrayBuffer());
  return applyImport(buffer, file.name, actor);
}

// ---------------------------------------------------------------------------
// Discussion comments (D14): separate from `activities` — writing a comment
// never touches the activity timeline. Only editor/admin may comment.
// ---------------------------------------------------------------------------

export async function createComment(kodeDisplay: string, body: string): Promise<{ id: string }> {
  await requireRole('editor');
  const actor = await requireActorIdentity();
  const text = body.trim();

  if (text.length === 0) {
    throw new ValidationError('Komentar tidak boleh kosong.');
  }
  if (text.length > 4000) {
    throw new ValidationError('Komentar terlalu panjang (maks 4000 karakter).');
  }

  return db.transaction(async (tx) => {
    const [finding] = await tx
      .select({ id: findings.id })
      .from(findings)
      .where(and(eq(findings.kodeDisplay, kodeDisplay), isNull(findings.deletedAt)));

    if (!finding) {
      throw new NotFoundError(`Temuan ${kodeDisplay} tidak ditemukan.`);
    }

    const [row] = await tx
      .insert(comments)
      .values({
        findingId: finding.id,
        authorUserId: actor.userId,
        authorEmail: actor.email,
        authorName: actor.name,
        body: text
      })
      .returning({ id: comments.id });

    return { id: row.id };
  });
}

export async function deleteComment(commentId: string): Promise<{ deleted: boolean }> {
  const userId = await requireRole('editor');
  await requireActorIdentity();

  return db.transaction(async (tx) => {
    const [row] = await tx.select().from(comments).where(eq(comments.id, commentId));
    if (!row) {
      throw new NotFoundError('Komentar tidak ditemukan.');
    }

    // Deleting someone else's comment requires admin (editor may delete own).
    if (row.authorUserId !== userId) {
      await requireRole('admin');
    }

    await tx.delete(comments).where(eq(comments.id, commentId));
    return { deleted: true };
  });
}

// ---------------------------------------------------------------------------
// Attachments: metadata in Postgres, bytes under `storage/attachments/`
// (outside `public/`). Served through an authenticated route handler.
// ---------------------------------------------------------------------------

export async function uploadAttachment(
  kodeDisplay: string,
  formData: FormData
): Promise<{ id: string; fileName: string }> {
  await requireRole('editor');
  const actor = await requireActorIdentity();

  const file = formData.get('file');
  if (!(file instanceof File)) {
    throw new ValidationError('Berkas wajib dipilih.');
  }
  if (file.size > MAX_ATTACHMENT_BYTES) {
    throw new ValidationError('Ukuran berkas melebihi 10 MB.');
  }

  const buffer = Buffer.from(await file.arrayBuffer());
  const resolved = resolveFile(buffer, file.name);
  if (!resolved) {
    throw new ValidationError('Jenis berkas tidak didukung (pdf, xlsx, docx, atau gambar).');
  }

  return db.transaction(async (tx) => {
    const [finding] = await tx
      .select({ id: findings.id })
      .from(findings)
      .where(and(eq(findings.kodeDisplay, kodeDisplay), isNull(findings.deletedAt)));

    if (!finding) {
      throw new NotFoundError(`Temuan ${kodeDisplay} tidak ditemukan.`);
    }

    const storagePath = `storage/attachments/${finding.id}/${randomUUID()}.${resolved.extension}`;
    await mkdir(`storage/attachments/${finding.id}`, { recursive: true });
    await writeFile(storagePath, buffer);

    const [row] = await tx
      .insert(attachments)
      .values({
        findingId: finding.id,
        fileName: file.name,
        storagePath,
        fileType: resolved.fileType,
        mimeType: resolved.mimeType,
        sizeBytes: file.size,
        uploadedByUserId: actor.userId,
        uploadedByEmail: actor.email
      })
      .returning({ id: attachments.id });

    await logActivity(tx, actor, {
      entityId: finding.id,
      action: 'Unggah Berkas',
      metadata: { fileName: file.name, fileType: resolved.fileType, sizeBytes: file.size }
    });

    return { id: row.id, fileName: file.name };
  });
}

export async function deleteAttachment(attachmentId: string): Promise<{ deleted: boolean }> {
  await requireRole('editor');
  const actor = await requireActorIdentity();

  return db.transaction(async (tx) => {
    const [row] = await tx.select().from(attachments).where(eq(attachments.id, attachmentId));
    if (!row) {
      throw new NotFoundError('Lampiran tidak ditemukan.');
    }

    await tx.delete(attachments).where(eq(attachments.id, attachmentId));
    try {
      await unlink(row.storagePath);
    } catch {
      // The row is gone; a missing file is not worth failing the request for.
    }

    await logActivity(tx, actor, {
      entityId: row.findingId,
      action: 'Unggah Berkas',
      metadata: { fileName: row.fileName, deleted: true }
    });

    return { deleted: true };
  });
}
