'use server';

/**
 * Finding mutations (task_plan.md Phase 5, D17/D23).
 *
 * Every write authenticates and authorizes server-side before touching the
 * database, runs inside a transaction, and appends an `activities` row with
 * the before/after diff (D13/D18). `activities` is append-only.
 *
 * Mutations created here are only those the UI actually uses — no placeholder
 * actions for future features.
 */

import { createHash } from 'node:crypto';
import { mkdir, writeFile } from 'node:fs/promises';

import { and, eq, isNull, isNotNull, sql } from 'drizzle-orm';
import * as XLSX from 'xlsx';

import { db } from '@/db/client';
import { activities, findings, importBatches } from '@/db/schema';
import { NotFoundError, ValidationError } from '@/lib/errors';
import { requireActorIdentity, requireRole } from '@/lib/rbac';
import { findingSchema, type FindingFormValues } from '../schemas/finding';
import type { ActivityAction, FindingStatus } from './types';
import { diffFields, hasChanges, type FieldDiff } from '../utils/diff';
import { diffOfficialFields, importIdentity, mapSheetRows } from '../utils/import-xlsx';

interface Actor {
  userId: string;
  email: string;
  name: string | null;
}

type Db = Parameters<Parameters<typeof db.transaction>[0]>[0];

/** Columns a manual edit may change; also the fields compared for the diff. */
const EDITABLE_FIELDS = [
  'noSatker',
  'tahun',
  'kodeTemuan',
  'kodeRekomendasi',
  'judulPemeriksaan',
  'uraianTemuan',
  'uraianRekomendasi',
  'nilaiTemuan',
  'status',
  'deskripsiTindakLanjut',
  'alasanDitolak',
  'tanggalTindakLanjut',
  'unitKerja'
] as const;

function parseInput(input: FindingFormValues) {
  const result = findingSchema.safeParse(input);
  if (!result.success) {
    throw new ValidationError(result.error.issues[0]?.message ?? 'Data temuan tidak valid.');
  }
  return result.data;
}

interface FindingRowInput {
  noSatker: string;
  tahun: number;
  kodeTemuan: string;
  kodeRekomendasi: string;
  judulPemeriksaan: string;
  uraianTemuan: string;
  uraianRekomendasi: string;
  nilaiTemuan: number;
  status: FindingStatus;
  deskripsiTindakLanjut: string;
  unitKerja: string;
  alasanDitolak?: string | null;
  tanggalTindakLanjut?: string | null;
}

function toRow(values: FindingRowInput) {
  return {
    noSatker: values.noSatker,
    tahun: values.tahun,
    kodeTemuan: values.kodeTemuan,
    kodeRekomendasi: values.kodeRekomendasi,
    judulPemeriksaan: values.judulPemeriksaan,
    uraianTemuan: values.uraianTemuan,
    uraianRekomendasi: values.uraianRekomendasi,
    // Exact numeric string — money never touches JS floating point (D8).
    nilaiTemuan: values.nilaiTemuan.toFixed(2),
    status: values.status,
    deskripsiTindakLanjut: values.deskripsiTindakLanjut,
    alasanDitolak: values.alasanDitolak ? values.alasanDitolak : null,
    tanggalTindakLanjut: values.tanggalTindakLanjut ? values.tanggalTindakLanjut : null,
    unitKerja: values.unitKerja
  };
}

async function logActivity(
  tx: Db,
  actor: Actor,
  entry: {
    entityId: string;
    entityType?: 'finding' | 'import_batch';
    action: ActivityAction;
    metadata: FieldDiff | Record<string, unknown>;
  }
) {
  await tx.insert(activities).values({
    entityType: entry.entityType ?? 'finding',
    entityId: entry.entityId,
    action: entry.action,
    metadata: entry.metadata,
    actorUserId: actor.userId,
    actorEmail: actor.email
  });
}

function isUniqueViolation(error: unknown): boolean {
  return (
    typeof error === 'object' && error !== null && (error as { code?: string }).code === '23505'
  );
}

export async function createFinding(input: FindingFormValues): Promise<{ kodeDisplay: string }> {
  await requireRole('editor');
  const values = parseInput(input);
  const actor = await requireActorIdentity();

  return db.transaction(async (tx) => {
    // `kode_display` is generated by the database trigger (D31).
    const [row] = await tx
      .insert(findings)
      // `kode_display` is filled by the BEFORE INSERT trigger (D31), so the
      // column is left to DEFAULT/NULL instead of being generated in the app.
      .values({ ...toRow(values), kodeDisplay: sql`default`, tanggalTerakhirUpdate: new Date() })
      .returning({ id: findings.id, kodeDisplay: findings.kodeDisplay });

    if (!row) {
      throw new ValidationError('Temuan gagal disimpan.');
    }

    await logActivity(tx, actor, {
      entityId: row.id,
      action: 'Tambah Temuan',
      metadata: { kodeDisplay: row.kodeDisplay }
    });

    return { kodeDisplay: row.kodeDisplay };
  });
}

export async function updateFinding(
  kodeDisplay: string,
  input: FindingFormValues
): Promise<{ changed: boolean; diff: FieldDiff }> {
  await requireRole('editor');
  const values = parseInput(input);
  const actor = await requireActorIdentity();

  return db.transaction(async (tx) => {
    const [current] = await tx
      .select()
      .from(findings)
      .where(and(eq(findings.kodeDisplay, kodeDisplay), isNull(findings.deletedAt)));

    if (!current) {
      throw new NotFoundError(`Temuan ${kodeDisplay} tidak ditemukan.`);
    }

    const row = toRow(values);
    const before = current as unknown as Record<string, unknown>;
    const after = { ...current, ...row } as unknown as Record<string, unknown>;
    const diff = diffFields(before, after, EDITABLE_FIELDS as unknown as string[]);

    if (!hasChanges(diff)) {
      return { changed: false, diff };
    }

    await tx.update(findings).set(row).where(eq(findings.id, current.id));
    await logActivity(tx, actor, {
      entityId: current.id,
      action: 'Perbarui Temuan',
      metadata: diff
    });

    return { changed: true, diff };
  });
}

export async function softDeleteFinding(kodeDisplay: string): Promise<{ deleted: boolean }> {
  await requireRole('editor');
  const actor = await requireActorIdentity();

  return db.transaction(async (tx) => {
    const [current] = await tx
      .select()
      .from(findings)
      .where(and(eq(findings.kodeDisplay, kodeDisplay), isNull(findings.deletedAt)));

    if (!current) {
      throw new NotFoundError(`Temuan ${kodeDisplay} tidak ditemukan.`);
    }

    await tx
      .update(findings)
      .set({ deletedAt: sql`now()` })
      .where(eq(findings.id, current.id));

    await logActivity(tx, actor, {
      entityId: current.id,
      action: 'Hapus Temuan',
      metadata: { kodeDisplay: current.kodeDisplay, softDelete: true }
    });

    return { deleted: true };
  });
}

/** Restore is admin-only (D12); never raw SQL by hand. */
export async function restoreFinding(kodeDisplay: string): Promise<{ restored: boolean }> {
  await requireRole('admin');
  const actor = await requireActorIdentity();

  return db.transaction(async (tx) => {
    const [current] = await tx
      .select()
      .from(findings)
      .where(and(eq(findings.kodeDisplay, kodeDisplay), isNotNull(findings.deletedAt)));

    if (!current) {
      throw new NotFoundError(`Temuan ${kodeDisplay} yang terhapus tidak ditemukan.`);
    }

    try {
      await tx.update(findings).set({ deletedAt: null }).where(eq(findings.id, current.id));
    } catch (error) {
      if (isUniqueViolation(error)) {
        throw new ValidationError(
          'Tidak bisa dipulihkan: sudah ada temuan aktif dengan identitas yang sama.'
        );
      }
      throw error;
    }

    await logActivity(tx, actor, {
      entityId: current.id,
      action: 'Pulihkan Temuan',
      metadata: { kodeDisplay: current.kodeDisplay }
    });

    return { restored: true };
  });
}

// ---------------------------------------------------------------------------
// XLSX import (D18/D19): direct upsert inside one transaction, per-row diff
// logged to `activities`, summary recorded in `import_batches`, source file
// kept under `storage/imports/` as an audit artifact.
// ---------------------------------------------------------------------------

export interface ImportSummary {
  batchId: string;
  fileName: string;
  rowsTotal: number;
  created: number;
  updated: number;
  unchanged: number;
  failed: number;
  status: 'completed' | 'completed_with_errors' | 'failed';
  skipped: { rowNumber: number; reason: string }[];
}

/** Imports are editor/admin only (D17); the whole file runs in one transaction. */
export async function importFindingsXlsx(formData: FormData): Promise<ImportSummary> {
  await requireRole('editor');
  const actor = await requireActorIdentity();

  const file = formData.get('file');
  if (!(file instanceof File)) {
    throw new ValidationError('Berkas XLSX wajib diunggah.');
  }
  if (!/\.(xlsx|xls)$/i.test(file.name)) {
    throw new ValidationError('Format berkas harus .xlsx atau .xls.');
  }

  const buffer = Buffer.from(await file.arrayBuffer());
  const fileHash = createHash('sha256').update(buffer).digest('hex');

  let sheetRows: Record<string, unknown>[];
  try {
    const workbook = XLSX.read(buffer, { type: 'buffer', cellDates: true });
    const sheetName = workbook.SheetNames[0];
    if (!sheetName) {
      throw new ValidationError('Berkas tidak memiliki lembar kerja.');
    }
    sheetRows = XLSX.utils.sheet_to_json<Record<string, unknown>>(workbook.Sheets[sheetName], {
      defval: ''
    });
  } catch (error) {
    if (error instanceof ValidationError) throw error;
    throw new ValidationError('Berkas XLSX tidak dapat dibaca.');
  }

  if (sheetRows.length === 0) {
    throw new ValidationError('Berkas tidak berisi baris data.');
  }

  const { records, skipped } = mapSheetRows(sheetRows);

  const summary = await db.transaction(async (tx) => {
    const [batch] = await tx
      .insert(importBatches)
      .values({
        fileName: file.name,
        fileHash,
        uploadedByUserId: actor.userId,
        uploadedByEmail: actor.email,
        startedAt: new Date(),
        status: 'pending',
        rowsTotal: sheetRows.length
      })
      .returning({ id: importBatches.id });

    if (!batch) {
      throw new ValidationError('Batch impor gagal dibuat.');
    }

    // Existing rows for the identities present in the file.
    const existingRows = await tx.select().from(findings).where(isNull(findings.deletedAt));
    const byIdentity = new Map(
      existingRows.map((row) => [
        importIdentity({
          noSatker: row.noSatker,
          tahun: row.tahun,
          kodeTemuan: row.kodeTemuan,
          kodeRekomendasi: row.kodeRekomendasi
        }),
        row
      ])
    );

    let created = 0;
    let updated = 0;
    let unchanged = 0;
    let failed = 0;
    const failures: string[] = skipped.map((row) => `Baris ${row.rowNumber}: ${row.reason}`);

    for (const record of records) {
      const identity = importIdentity(record);
      const existing = byIdentity.get(identity);

      // Savepoint per row: one bad row must not abort the whole import.
      try {
        if (!existing) {
          const [inserted] = await tx
            .insert(findings)
            .values({
              ...toRow(record),
              kodeDisplay: sql`default`,
              tanggalTerakhirUpdate: record.tanggalTerakhirUpdate,
              lastSeenInImportAt: new Date(),
              lastImportBatchId: batch.id
            })
            .returning({ id: findings.id, kodeDisplay: findings.kodeDisplay });

          await logActivity(tx, actor, {
            entityId: inserted.id,
            action: 'Tambah Temuan',
            metadata: {
              source: 'import-xlsx',
              importBatchId: batch.id,
              kodeDisplay: inserted.kodeDisplay
            }
          });
          created += 1;
          continue;
        }

        const before = existing as unknown as Record<string, unknown>;
        const after = {
          ...existing,
          ...toRow(record),
          tanggalTerakhirUpdate: record.tanggalTerakhirUpdate
        } as unknown as Record<string, unknown>;
        const diff = diffOfficialFields(before, after);

        await tx
          .update(findings)
          .set({
            status: record.status,
            alasanDitolak: record.alasanDitolak,
            deskripsiTindakLanjut: record.deskripsiTindakLanjut,
            tanggalTindakLanjut: record.tanggalTindakLanjut,
            tanggalTerakhirUpdate: record.tanggalTerakhirUpdate,
            nilaiTemuan: record.nilaiTemuan.toFixed(2),
            lastSeenInImportAt: new Date(),
            lastImportBatchId: batch.id
          })
          .where(eq(findings.id, existing.id));

        if (hasChanges(diff)) {
          await logActivity(tx, actor, {
            entityId: existing.id,
            action: 'Perbarui Temuan',
            metadata: { source: 'import-xlsx', importBatchId: batch.id, ...diff }
          });
          updated += 1;
        } else {
          unchanged += 1;
        }
      } catch (error) {
        failed += 1;
        const detail = error instanceof Error ? error.message : 'kesalahan tidak dikenal';
        if (failures.length < 50) {
          failures.push(`Baris ${record.kodeTemuan}/${record.tahun}: ${detail}`);
        }
      }
    }

    const status: ImportSummary['status'] =
      records.length === 0
        ? 'failed'
        : failed > 0 || skipped.length > 0
          ? 'completed_with_errors'
          : 'completed';

    // Best-effort audit copy; the database remains the source of truth.
    let storagePath: string | null = `storage/imports/${batch.id}.xlsx`;
    try {
      await mkdir('storage/imports', { recursive: true });
      await writeFile(storagePath, buffer);
    } catch {
      storagePath = null;
      failures.push('Berkas sumber gagal disimpan ke storage/imports.');
    }

    await tx
      .update(importBatches)
      .set({
        finishedAt: new Date(),
        status,
        rowsCreated: created,
        rowsUpdated: updated,
        rowsUnchanged: unchanged,
        rowsFailed: failed,
        errorSummary: failures.length > 0 ? failures.slice(0, 20).join('\n') : null,
        storagePath
      })
      .where(eq(importBatches.id, batch.id));

    await logActivity(tx, actor, {
      entityId: batch.id,
      entityType: 'import_batch',
      action: 'Impor XLSX',
      metadata: {
        fileName: file.name,
        rowsTotal: sheetRows.length,
        created,
        updated,
        unchanged,
        failed,
        skipped: skipped.length
      }
    });

    return {
      batchId: batch.id,
      fileName: file.name,
      rowsTotal: sheetRows.length,
      created,
      updated,
      unchanged,
      failed,
      status,
      skipped
    } satisfies ImportSummary;
  });

  return summary;
}
